# Generated by Django 5.1.6 on 2025-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('qsar', '0002_gbmtdatasplit_embeddingcalculator_moleculeclusters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingstrategy',
            name='descriptors',
            field=models.ManyToManyField(to='qsar.embeddingcalculator'),
        ),
    ]
