# Generated by Django 5.1.6 on 2025-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_mappingstrategy_descriptors'),
        ('qsar', '0002_gbmtdatasplit_embeddingcalculator_moleculeclusters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingstrategy',
            name='embeddings',
            field=models.ManyToManyField(to='qsar.embeddingcalculator'),
        ),
    ]
