# Generated by Django 5.1.6 on 2025-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HyperparameterOptimizationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchSpace', models.JSONField(blank=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.modelperformancemetric')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('trainingStrategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategies', to='models.trainingstrategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ValueAggregationFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corePackage', models.CharField(default='genui.models.genuimodels', max_length=1024)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ModelPerfomanceNN',
            new_name='ModelPerformanceNN',
        ),
        migrations.RemoveField(
            model_name='basicvalidationstrategy',
            name='validSetSize',
        ),
        migrations.RemoveField(
            model_name='validationstrategy',
            name='modelInstance',
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='trainingStrategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validationStrategies', to='models.trainingstrategy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RandomSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('testFraction', models.FloatField()),
                ('seed', models.IntegerField(blank=True, default=42)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.AddField(
            model_name='basicvalidationstrategy',
            name='dataSplit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.datasplit'),
        ),
        migrations.CreateModel(
            name='GridSearchOptimization',
            fields=[
                ('hyperparameteroptimizationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.hyperparameteroptimizationstrategy')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.hyperparameteroptimizationstrategy',),
        ),
        migrations.CreateModel(
            name='OptunaOptimization',
            fields=[
                ('hyperparameteroptimizationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.hyperparameteroptimizationstrategy')),
                ('nTrials', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.hyperparameteroptimizationstrategy',),
        ),
        migrations.AddField(
            model_name='hyperparameteroptimizationstrategy',
            name='scoreAggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategies', to='models.valueaggregationfunction'),
        ),
        migrations.CreateModel(
            name='BootstrapSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('nBootstraps', models.IntegerField()),
                ('seed', models.IntegerField(blank=True, default=42)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrappedSplits', to='models.datasplit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
    ]
