# Generated by Django 5.1.6 on 2025-02-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models', '0003_remove_validationstrategy_modelinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='basicvalidationstrategy',
            name='validSetSize',
        ),
        migrations.CreateModel(
            name='RandomSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('testSize', models.FloatField()),
                ('randomSeed', models.IntegerField(blank=True, default=42)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.AddField(
            model_name='basicvalidationstrategy',
            name='dataSplit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.datasplit'),
        ),
    ]
