# Generated by Django 5.1.6 on 2025-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_datasplit_hyperparameteroptimizationstrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrapsplit',
            name='nBootstraps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='randomsplit',
            name='testFraction',
            field=models.FloatField(default=0.8),
        ),
    ]
