# Generated by Django 5.1.6 on 2025-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_datasplit_hyperparameteroptimizationstrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='scoreAggregation',
            field=models.CharField(choices=[('mean', 'np.mean'), ('median', 'np.median'), ('max', 'np.max'), ('min', 'np.min')], max_length=128),
        ),
    ]
