# Generated by Django 5.1.6 on 2025-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_bootstrapsplit_nbootstraps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformance',
            name='validationIndex',
            field=models.IntegerField(default=-1000),
            preserve_default=False,
        ),
    ]
