# Generated by Django 5.1.6 on 2025-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_datasplit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomsplit',
            old_name='randomSeed',
            new_name='seed',
        ),
        migrations.RenameField(
            model_name='randomsplit',
            old_name='testSize',
            new_name='testFraction',
        ),
    ]
