# Generated by Django 5.1.6 on 2025-03-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_hyperparameteroptimizationstrategy_scoreaggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='scoreAggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategy', to='models.valueaggregationfunction'),
        ),
    ]
