# Generated by Django 5.1.6 on 2025-06-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_bootstrapsplit_nbootstraps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparameterOptimizationPerformance',
            fields=[
                ('modelperformance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.modelperformance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.modelperformance',),
        ),
        migrations.AddField(
            model_name='modelperformancecv',
            name='validationIndex',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
