# Generated by Django 5.1.6 on 2025-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_rename_randomseed_randomsplit_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
