# Generated by Django 5.1.6 on 2025-04-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_hyperparameteroptimizationstrategy_scoreaggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='trainingStrategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategy', to='models.trainingstrategy'),
        ),
    ]
