# Generated by Django 5.2.7 on 2025-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_hyperparameteroptimizationperformance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='scoreAggregation',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='randomsplit',
            name='testFraction',
            field=models.FloatField(default=0.2),
        ),
        migrations.DeleteModel(
            name='ValueAggregationFunction',
        ),
    ]
