# Generated by Django 5.1.6 on 2025-04-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_hyperparameteroptimizationstrategy_scoreaggregation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GridSearchStrategy',
            new_name='GridSearchOptimization',
        ),
        migrations.RenameModel(
            old_name='OptunaStrategy',
            new_name='OptunaOptimization',
        ),
        migrations.AddField(
            model_name='hyperparameteroptimizationstrategy',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.modelperformancemetric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='scoreAggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperParamOptStrategies', to='models.valueaggregationfunction'),
        ),
    ]
