# Generated by Django 5.1.6 on 2025-04-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_gridsearchstrategy_gridsearchoptimization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('nBootstraps', models.IntegerField()),
                ('seed', models.IntegerField(blank=True, default=42)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrappedSplits', to='models.datasplit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
    ]
