# Generated by Django 5.2.7 on 2025-10-08 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_hyperparameteroptimizationstrategy_scoreaggregation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameteroptimizationstrategy',
            name='metric',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='metric',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='validationstrategy',
            name='metrics',
        ),
        migrations.DeleteModel(
            name='ModelPerformanceMetric',
        ),
        migrations.AddField(
            model_name='validationstrategy',
            name='metrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
    ]
