# Generated by Django 5.1.6 on 2025-10-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_hyperparameteroptimizationstrategy_metric_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ROCCurvePoint',
            new_name='MetricCurvePoint',
        ),
        migrations.RenameField(
            model_name='metriccurvepoint',
            old_name='fpr',
            new_name='independent',
        ),
        migrations.RenameField(
            model_name='modelperformancecv',
            old_name='validationIndex',
            new_name='validationStrategyIndex',
        ),
    ]
