# Generated by Django 5.1.6 on 2025-02-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('models', '0004_datasplit_and_more'),
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeClusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='GBMTDataSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('testSize', models.FloatField()),
                ('nFolds', models.IntegerField()),
                ('clustering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.moleculeclusters')),
                ('customTestList', models.ManyToManyField(blank=True, to='compounds.molecule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.CreateModel(
            name='TemporalSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('timeSplit', models.FloatField()),
                ('timeProp', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.CreateModel(
            name='BootstrapSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('nBootstraps', models.IntegerField()),
                ('randomSeed', models.IntegerField(blank=True, default=42)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrappedSplits', to='models.datasplit')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.CreateModel(
            name='FPSimilarityClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('IDProp', models.CharField(blank=True, max_length=128)),
                ('FPCalculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.descriptorgroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.CreateModel(
            name='RandomClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('seed', models.IntegerField(default=42)),
                ('nClusters', models.IntegerField(blank=True)),
                ('IDProp', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.CreateModel(
            name='ScaffoldClusters',
            fields=[
                ('moleculeclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.moleculeclusters')),
                ('scaffold', models.CharField(choices=[('BemisMurckoRDKit', 'BemisMurckoRDKit'), ('BemisMurcko', 'BemisMurcko')], default='BemisMurckoRDKit', max_length=128)),
                ('IDProp', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.moleculeclusters',),
        ),
        migrations.CreateModel(
            name='ClusterSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('testSize', models.FloatField()),
                ('nFolds', models.IntegerField()),
                ('randomSeed', models.IntegerField(blank=True, default=42)),
                ('customTestList', models.ManyToManyField(blank=True, to='compounds.molecule')),
                ('clustering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.moleculeclusters')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.CreateModel(
            name='GBMTRandomSplit',
            fields=[
                ('gbmtdatasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.gbmtdatasplit')),
                ('randomSeed', models.IntegerField(blank=True, default=42)),
                ('nInitialClusters', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.gbmtdatasplit',),
        ),
        migrations.CreateModel(
            name='ScaffoldSplit',
            fields=[
                ('datasplit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.datasplit')),
                ('scaffold', models.CharField(choices=[('BemisMurckoRDKit', 'BemisMurckoRDKit'), ('BemisMurcko', 'BemisMurcko')], default='BemisMurckoRDKit', max_length=128)),
                ('testSize', models.FloatField()),
                ('nFolds', models.IntegerField()),
                ('customTestList', models.ManyToManyField(blank=True, to='compounds.molecule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.datasplit',),
        ),
        migrations.CreateModel(
            name='FPSimilarityLeaderPickerClusters',
            fields=[
                ('fpsimilarityclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.fpsimilarityclusters')),
                ('similarityThreshold', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.fpsimilarityclusters',),
        ),
        migrations.CreateModel(
            name='FPSimilarityMaxMinClusters',
            fields=[
                ('fpsimilarityclusters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.fpsimilarityclusters')),
                ('nClusters', models.IntegerField(blank=True)),
                ('seed', models.IntegerField(blank=True, default=42)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('qsar.fpsimilarityclusters',),
        ),
    ]
