# Generated by Django 5.1.6 on 2025-04-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('qsar', '0002_moleculeclusters_gbmtdatasplit_qsprpredsklearnmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DescriptorGroup',
            new_name='EmbeddingCalculator',
        ),
        migrations.RenameField(
            model_name='qsartrainingstrategy',
            old_name='descriptors',
            new_name='embeddings',
        ),
    ]
