# Generated by Django 5.1.6 on 2025-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0002_gbmtdatasplit_embeddingcalculator_moleculeclusters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbmtdatasplit',
            name='testFraction',
            field=models.FloatField(blank=True, default=0.8, null=True),
        ),
        migrations.AlterField(
            model_name='gbmtrandomsplit',
            name='nInitialClusters',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
