# Generated by Django 5.1.6 on 2025-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0002_moleculeclusters_gbmtdatasplit_temporalsplit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrapsplit',
            old_name='randomSeed',
            new_name='seed',
        ),
        migrations.RenameField(
            model_name='clustersplit',
            old_name='randomSeed',
            new_name='seed',
        ),
        migrations.RenameField(
            model_name='clustersplit',
            old_name='testSize',
            new_name='testFraction',
        ),
        migrations.RenameField(
            model_name='gbmtdatasplit',
            old_name='testSize',
            new_name='testFraction',
        ),
        migrations.RenameField(
            model_name='gbmtrandomsplit',
            old_name='randomSeed',
            new_name='seed',
        ),
        migrations.RenameField(
            model_name='scaffoldsplit',
            old_name='testSize',
            new_name='testFraction',
        ),
        migrations.AlterField(
            model_name='scaffoldclusters',
            name='scaffold',
            field=models.CharField(choices=[('BemisMurcko', 'BemisMurcko'), ('BemisMurckoRDKit', 'BemisMurckoRDKit')], default='BemisMurckoRDKit', max_length=128),
        ),
        migrations.AlterField(
            model_name='scaffoldsplit',
            name='scaffold',
            field=models.CharField(choices=[('BemisMurcko', 'BemisMurcko'), ('BemisMurckoRDKit', 'BemisMurckoRDKit')], default='BemisMurckoRDKit', max_length=128),
        ),
    ]
