# Generated by Django 5.1.6 on 2025-04-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_rename_descriptorgroup_embeddingcalculator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldCalculator',
            fields=[
                ('embeddingcalculator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.embeddingcalculator')),
            ],
            options={
                'abstract': False,
            },
            bases=('qsar.embeddingcalculator',),
        ),
        migrations.RemoveField(
            model_name='clustersplit',
            name='clustering',
        ),
        migrations.RemoveField(
            model_name='clustersplit',
            name='customTestList',
        ),
        migrations.RemoveField(
            model_name='clustersplit',
            name='datasplit_ptr',
        ),
        migrations.RemoveField(
            model_name='clustersplit',
            name='nFolds',
        ),
        migrations.RemoveField(
            model_name='clustersplit',
            name='testFraction',
        ),
        migrations.RemoveField(
            model_name='fpsimilarityclusters',
            name='IDProp',
        ),
        migrations.RemoveField(
            model_name='gbmtdatasplit',
            name='customTestList',
        ),
        migrations.RemoveField(
            model_name='randomclusters',
            name='IDProp',
        ),
        migrations.RemoveField(
            model_name='scaffoldclusters',
            name='IDProp',
        ),
        migrations.RemoveField(
            model_name='scaffoldsplit',
            name='customTestList',
        ),
        migrations.RemoveField(
            model_name='scaffoldsplit',
            name='datasplit_ptr',
        ),
        migrations.RemoveField(
            model_name='scaffoldsplit',
            name='nFolds',
        ),
        migrations.RemoveField(
            model_name='scaffoldsplit',
            name='testFraction',
        ),
        migrations.AddField(
            model_name='clustersplit',
            name='gbmtdatasplit_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.gbmtdatasplit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scaffoldsplit',
            name='gbmtdatasplit_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qsar.gbmtdatasplit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gbmtdatasplit',
            name='nFolds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gbmtdatasplit',
            name='testFraction',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='randomclusters',
            name='seed',
            field=models.IntegerField(blank=True, default=42),
        ),
        migrations.AlterField(
            model_name='scaffoldclusters',
            name='scaffold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.scaffoldcalculator'),
        ),
        migrations.AlterField(
            model_name='scaffoldsplit',
            name='scaffold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsar.scaffoldcalculator'),
        ),
        migrations.DeleteModel(
            name='BootstrapSplit',
        ),
    ]
