# Generated by Django 5.1.6 on 2025-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_alter_gbmtdatasplit_testfraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbmtdatasplit',
            name='testFraction',
            field=models.FloatField(blank=True, default=0.2, null=True),
        ),
    ]
