# Generated by Django 5.1.6 on 2025-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_rename_randomseed_bootstrapsplit_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptorgroup',
            name='arguments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
