# Generated by Django 5.1.6 on 2025-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0003_rename_descriptorgroup_embeddinggroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qsartrainingstrategy',
            old_name='descriptors',
            new_name='embeddings',
        ),
    ]
