# Generated by Django 5.1.6 on 2025-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0004_descriptorgroup_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorgroup',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
