# Generated by Django 5.1.6 on 2025-04-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('qsar', '0004_rename_descriptors_qsartrainingstrategy_embeddings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbeddingGroup',
            new_name='EmbeddingCalculator',
        ),
    ]
