# Generated by Django 5.1.6 on 2025-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0005_alter_descriptorgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorgroup',
            name='arguments',
            field=models.JSONField(default=dict),
        ),
    ]
