# Generated by Django 5.1.6 on 2025-03-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_algorithm_name'),
        ('qsar', '0006_alter_descriptorgroup_arguments'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSARAlgorithm',
            fields=[
                ('algorithm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.algorithm')),
                ('arguments', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('models.algorithm',),
        ),
    ]
