# Generated by Django 5.1.6 on 2025-03-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsar', '0007_qsaralgorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QSARAlgorithm',
        ),
    ]
